name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # This workflow runs when you push to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    # Step 3: Build the Docker image
    - name: Build the Docker image
      run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/sumanreddy:latest .

    # Step 4: Push the Docker image to Docker Hub
    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/sumanreddy:latest
